# Generated by Django 2.2.3 on 2019-07-26 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('donador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donador',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.Hospital'),
        ),
    ]
