# Generated by Django 2.2.3 on 2020-06-25 15:21

import apps.donador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donador',
            name='fecha_nacimiento',
            field=models.DateField(validators=[apps.donador.models.check_date]),
        ),
    ]
