# Generated by Django 2.2.3 on 2019-11-06 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('donador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donador',
            name='groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
