# Generated by Django 2.2.3 on 2020-07-28 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donador', '0003_desactivar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desactivar',
            old_name='Donador',
            new_name='donador',
        ),
    ]
