# Generated by Django 2.2.3 on 2020-07-30 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donador', '0004_auto_20200728_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donador',
            old_name='factor_sanguineo',
            new_name='factor_RH',
        ),
    ]
