# Generated by Django 2.2.3 on 2020-08-03 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donador', '0005_auto_20200730_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desactivar',
            old_name='fecha_donacion',
            new_name='fecha_desactivar',
        ),
    ]
