# Generated by Django 2.2.3 on 2020-08-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donador', '0006_auto_20200803_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desactivar',
            name='motivo',
            field=models.IntegerField(),
        ),
    ]
