# Generated by Django 2.2.3 on 2020-08-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donador', '0007_auto_20200804_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='donador',
            name='dni',
            field=models.IntegerField(default=13),
            preserve_default=False,
        ),
    ]
