# Generated by Django 2.2.3 on 2020-09-02 22:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/logos'),
            preserve_default=False,
        ),
    ]
