# Generated by Django 2.2.3 on 2020-06-30 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donacion',
            name='user',
        ),
    ]
