# Generated by Django 2.2.3 on 2019-09-30 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0005_empleado_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='group',
            new_name='grupo',
        ),
    ]
