# Generated by Django 2.2.3 on 2019-09-30 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0006_auto_20190929_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='grupo',
        ),
    ]
